### ISSUE TITLE
Resolving IDbConnectionFactory in .NET Core 2.1 WebApi for MultiTenant Application

### ISSUE THREAD

**Issue by suryasreepada** [masterinspire/TheOne.OrmLite#3]
Thanks for your efforts in creating and maintaining this repo.
This enabled us to go for .NET Core for Oracle databases.

Need help in finding the right approach for resolving IDbConnectionFactory in .NET Core 2.1 WebApi Application where the connection string differs for each request.
Due to this restriction, IDbConnectionFactory cannot be a singleton.

Please help.

Here is the code I have for now. Not sure if this works without any issues.

services.AddScoped(x => 
            {
                var currentTenant = x.GetService<ITenantProvider>().Current;
                return new DbConnectionFactory(currentTenant.ConnectionString, GetDialectProvider(currentTenant));
            });

Dialect may change based on the tenant. Could be SQL Server or Oracle.

FYI, I am seeing below error in logs. Not sure this is related to IDbConnectionFactory not being singleton.
This is not a network issue since other applications are able to access the same database server.
May be issue with connection pooling.

Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-12545: Network Transport: Unable to resolve connect hostname ---> OracleInternal.Network.NetworkException (0x80004005): ORA-12545: Network Transport: Unable to resolve connect hostname ---> System.Net.Sockets.SocketException (11001): No such host is known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at OracleInternal.Network.TcpTransportAdapter.Connect(ConnectionOption conOption)
   at OracleInternal.Network.OracleCommunication.DoConnect(String tnsDescriptor)
   at OracleInternal.ServiceObjects.OracleConnectionImpl.Connect(ConnectionString cs, Boolean bOpenEndUserSession, OracleConnection connRefForCriteria, String instanceName)
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
   at TheOne.OrmLite.Core.OrmLiteDialectProviderBase.OpenAsync(IDbConnection db, CancellationToken token)
   at TheOne.OrmLite.Core.Definition.OrmLiteDbConnection.OpenAsync(CancellationToken token)
   at TheOne.OrmLite.Core.OrmLiteConnectionFactory.OpenDbConnectionAsync(CancellationToken token)

**Comment by masterinspire** [comment]
You should use `IDbConnectionFactory` as singleton.

> the connection string differs for each request

OrmLite supports **multiple nested named connections**, register all your connections when you create  `OrmLiteConnectionFactory`, then `OpenDbConnection` by name, checkout [ConnectionFactoryTests](https://github.com/masterinspire/TheOne.OrmLite/blob/acf15b973f0d1d022cb1b2e61908de64ca708637/src/TheOne.OrmLite.Tests/All/Misc/ConnectionFactoryTests.cs#L105) for more examples:

```csharp
        public void Can_open_multiple_nested_connections() {
            var factory = new OrmLiteConnectionFactory(Config.SqliteMemoryDb, SqliteDialect.Provider);
            factory.RegisterConnection("SqlServer", Config.SqlServerDb, SqlServerDialect.Provider);
            factory.RegisterConnection("sqlite-file", Config.SqliteFileDb, SqliteDialect.Provider);

            var results = new List<Person>();
            using (var db = factory.OpenDbConnection()) {
                db.DropAndCreateTable<Person>();
                db.Insert(new Person { Id = 1, Name = "1) :memory:" });
                db.Insert(new Person { Id = 2, Name = "2) :memory:" });

                using (var db2 = factory.OpenDbConnection("SqlServer")) {
                    db2.CreateTable<Person>(true);
                    db2.Insert(new Person { Id = 3, Name = "3) Database1.mdf" });
                    db2.Insert(new Person { Id = 4, Name = "4) Database1.mdf" });

                    using (var db3 = factory.OpenDbConnection("sqlite-file")) {
                        db3.CreateTable<Person>(true);
                        db3.Insert(new Person { Id = 5, Name = "5) db.sqlite" });
                        db3.Insert(new Person { Id = 6, Name = "6) db.sqlite" });

                        results.AddRange(db.Select<Person>());
                        results.AddRange(db2.Select<Person>());
                        results.AddRange(db3.Select<Person>());
                    }
                }
            }

            Console.WriteLine(results.ToJson());
            var ids = results.ConvertAll(x => x.Id);
            Assert.AreEqual(new[] { 1, 2, 3, 4, 5, 6 }, ids);
        }
```

* * *

Thanks for you feedback. :smile: Please let me know if you have other problems.

**Comment by suryasreepada** [comment]
Thanks for your response. I tried this approach and works as expected.

Here is another scenario I am trying to solve. Appreciate your help.

I have a configuration DB where connection strings (around 4 for now and may go up in the future) are stored in an encrypted format.
There is a Service class which reads these connection strings from Database through Repository class.

Trying to find out how to inject connection factory as a singleton with these connections strings along with Config DB connection.

**Comment by masterinspire** [comment]
use config db as default db.

```csharp
            services.AddSingleton<IDbConnectionFactory>(provider => {
                var factory = new OrmLiteConnectionFactory("Config DB", new SqlServer2017OrmLiteDialectProvider());
                using (var db = factory.OpenDbConnection()) {
                    // manually create an instance of your service class, 
                    // read config and RegisterConnection, etc.
                }
                return factory;
            });
```

**don't use static DialectProvider instance**.

you may need to restart your app if your config db changes. 

then use IDbConnection as `Scoped `or `Transient`.

```csharp
            services.AddScoped<IDbConnection>(provider => {
                var factory = provider.GetRequiredService<IDbConnectionFactory>();
                // var dbName = "some name from some where";
                return factory.OpenDbConnection(/* dbName */);
            });
```

**Comment by suryasreepada** [comment]
#masterinspire Thanks for your suggestion.

I have implemented almost a similar solution as you suggested.
