### ISSUE TITLE
OrmLiteIgnoreOnSelect attribute is not working

### ISSUE THREAD

**Issue by suryasreepada** [masterinspire/TheOne.OrmLite#4]
I have tried using OrmLiteIgnoreOnSelect attribute and generated Query still has the column name in SELECT list.

Can you please check?

**Comment by masterinspire** [comment]
Actually, `OrmLiteIgnoreOnSelectAttribute` is currently not used.

But you can exclude your column from your poco, that should work. e.g.

If you hava a table like this:

```csharp
        public class DatabaseTable {

            public int Id { get; set; }
            public string Name { get; set; }
            public string Simple { get; set; }

        }
```

And you want to ingore `Simple` column:

```csharp
        public class DatabaseTableOutput {

            public int Id { get; set; }
            public string Name { get; set; }

        }
```

Then you can get your SELECT list like this

```csharp
        var q = db.From<DatabaseTable>().Where(x => x.Name == "someone");
        List<DatabaseTableOutput> list = db.Select<DatabaseTableOutput>(q);
```

OrmLite will automatically map your database model to your output model.

```sql
SELECT "Id", "Name" 
FROM "DatabaseTable"
WHERE ("Name" = @0)
```
